### PR TITLE
Implement Patch in C++

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
#### Methods needed for the new DisplayLayer refactor
* [x] `splice(start, deletedExtent, insertedExtent)`
* [x] `spliceOld(start, deletedExtent, insertedExtent)`
* [x] `getHunks()`
* [x] `getHunkInOldRange(oldStart, oldEnd)`
* [x] `getHunkInNewRange(newStart, newEnd)`
* [x] `hunkForOldPosition(oldStart)`
* [x] `hunkForNewPosition(oldStart)`

#### Other methods needed to for existing use cases
* [x] `splice(start, deletedExtent, insertedExtent, deletedText, insertedText)`
* [x] `compose`
* [x] `invert`
* [x] `serialize`
* [x] `deserialize`

### CODE REVIEW

**Comment by nathansobo** [comment]
@maxbrunsfeld This should be good to merge as soon as we figure out these linker errors on Travis 😿.

**Comment by nathansobo** [comment]
Trying to run the JS tests only to see if this is related to the configuration of the native tests.

**Comment by nathansobo** [comment]
Okay, looks like it's the configuration of the test target on Linux.

**Comment by nathansobo** [comment]
I wonder if this has something to do with trying to link the tests executable against V8 since we include `nan.h` in `patch.cc`. We do that just so we can use `Nan::Maybe`.

**Comment by nathansobo** [comment]
Building the tests without the `--debug` flag works on Linux. Not sure why `--debug` causes linker errors.

**Comment by nathansobo** [comment]
Okay, I figured it out. I think when we compiled the `tests` executable with GCC, the default optimization level of `-O0` was causing a bunch of V8 symbol references from `nan.h` to be retained in the object files. When building a shared library this doesn't matter because they can be resolved at load time, but when building an executable these symbols need to be resolved eagerly and since we don't actually have Node as a library, the linker fails.

Replacing `-O0` with `-Og` in the `Debug` configuration on Linux applies "debugger-friendly" optimizations and seems to do enough eliminate the undefined references in `nan.h` since we don't use them in `patch.cc`. The docs claim that `-Og` won't apply any aggressive optimizations that could interfere with debugging.

**Comment by maxbrunsfeld** [comment]
Yeah, so `HunkForPosition` is the only method that depends on v8's `Maybe` type, and we don't call this method in our tests, so if we enable *any* optimizations at all, the method will be removed from the executable, eliminating the v8 references.

In light of https://github.com/atom/buffer-offset-index/pull/2, we might want to just remove the v8 dependency from our 'core' Patch code, and only use it in `binding.cc`. We could just represent the maybe value as a `std::pair<Hunk, bool>` or something.

**Comment by nathansobo** [comment]
There's a boost header-only library that implements optionals that I think is going to be standardized in C++17.

**Pull request merged**
